#SMC HPA definition yaml
---
{{- if .Values.smc.autoscaling }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smc-hpa
  namespace: {{ .Release.Namespace }}
  labels: {{- include "siebel.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: smc
{{ .Values.smc.autoscaling | toYaml | indent 2 }}
{{- end }}

#SAI kubernetes yaml
---
apiVersion: v1
kind: Service
metadata:
  name: smc
  namespace: {{ .Release.Namespace }}
  labels: {{- include "siebel.labels" . | nindent 4 }}
    app.kubernetes.io/component: saiservice
spec:
  type: NodePort
  ports:
  - name: tomcat-port
    port: 4430
  {{- if .Values.monitoring.enableMonitoring }}
  - name: jmx-metrics
    port: 8088
  {{- end }}
  selector: {{- include "siebel.selectorLabels" . | nindent 4 }}
    app.siebel.tier: sai
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: smc
  labels: {{- include "siebel.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "siebel.selectorLabels" . | nindent 6 }}
      app.siebel.tier: sai
  serviceName: smc
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels: {{- include "siebel.labels" . | nindent 8 }}
        app.siebel.tier: sai
    spec:
      {{- if .Values.smc.affinity }}
      affinity: {{ .Values.smc.affinity | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ template "siebel.image" . }}
          imagePullPolicy: {{ .Values.image.siebel.pullPolicy | default "IfNotPresent" }}
          name: smc
          ports:
          - containerPort: 4430
            name: tomcat-port
          {{- if .Values.monitoring.enableMonitoring }}
          - containerPort: 8088
            name: jmx-metrics
          {{- end }}
          volumeMounts:
          - name: persist-storage
            mountPath: /persistent
            subPath: {{ .Release.Namespace | upper }}/SAI
          - name: keystore
            mountPath: /siebel/mde/applicationcontainer_external/siebelcerts/keystore.jks
            subPath: keystore.jks
          - name: keystore
            mountPath: /siebel/mde/applicationcontainer_external/siebelcerts/truststore.jks
            subPath: truststore.jks
          - name: keystore
            mountPath: /siebel/mde/tls_certs/ca.cert.pem
            subPath: ca.cert.pem
          - name: keystore
            mountPath: /siebel/mde/tls_certs/ca.key.pem
            subPath: ca.key.pem
          - name: keystore
            mountPath: /siebel/mde/tls_certs/server.pem
            subPath: server.pem
          {{- if .Values.monitoring.enableMonitoring }}
          - name: prometheus-jmx-config
            mountPath: /config/prometheus-jmx-config.yaml
            subPath: prometheus-jmx-config.yaml
          {{- end }}
          {{- range $index, $val := .Values.storage }}
          - name: sfs-storage-{{ $index }}
            mountPath: /sfs{{ $index }}
            subPath: {{ $.Release.Namespace | upper }}/FS
          {{- end }}
          env:
          {{- if .Values.monitoring.enableMonitoring }}
          - name: JMX_OPTS
            value: "-javaagent:/config/jmx_prometheus_javaagent-0.20.0.jar=8088:/config/prometheus-jmx-config.yaml"
          {{- end }}
          {{- if .Values.smc.envlist }}
          {{ .Values.smc.envlist | toYaml | nindent 10 }}
          {{- end }}
          - name: containerMode
            value: "SAI"
          - name: SBL_HEAP_OPTS
            value: "-Xms500m -Xmx4G"
          livenessProbe: {{ .Values.saiLivenessProbe | toYaml | nindent 12 }}
          readinessProbe: {{ .Values.saiReadinessProbe | toYaml | nindent 12 }}
          resources: {{ .Values.saiResources | toYaml | nindent 12 }}
          securityContext:
            runAsUser: 1000
        {{- if .Values.logging.enableLogging }}
        - image: {{ template "loggingCollector.image" . }}
          name: log-collector
          imagePullPolicy: {{ .Values.logging.image.imagePullPolicy | default "IfNotPresent" }}
          terminationMessagePolicy: FallbackToLogsOnError
          env:
          - name: CONTAINER_TYPE
            value: "smc"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
               fieldRef:
                 fieldPath: spec.nodeName
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: FLUENTD_ARGS
            value: "-c /etc/fluent/fluent.conf"
          - name:  FLUENT_FORWARD_HOST
            value: {{ .Values.logging.aggregatorInfo.svcName }}.{{ .Release.Namespace }}.svc.cluster.local
          - name:  FLUENT_FORWARD_PORT
            value: "{{ .Values.logging.aggregatorInfo.portNo }}"
          volumeMounts:
          - name: persist-storage
            mountPath: /persistent
            subPath: {{ .Release.Namespace | upper }}/SAI
          {{- include "logging.smcFluentdConfVolume" . | nindent 10 }}
          {{- include "logging.logFormat1Volume" . | nindent 10 }}
          {{- include "logging.logFormat2Volume" . | nindent 10 }}
          {{- include "logging.logFormat3Volume" . | nindent 10 }}
          {{- include "logging.logFormat4Volume" . | nindent 10 }}
          {{- include "logging.logFilterVolume" . | nindent 10 }}
          {{- include "logging.logForwarderVolume" . | nindent 10 }}
          resources: {{ .Values.logging.logCollectorResources | toYaml | nindent 12 }}
        {{- end }}
      initContainers:
        - name: persist-folders
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          image: {{ template "busybox.image" . }}
          command:
            - sh
            - -c
            - mkdir -p /work-dir/{{ .Release.Namespace | upper }}/SAI;
              chown -R 1000:1000 /work-dir/{{ .Release.Namespace | upper }}/SAI;
          volumeMounts:
          - name: persist-storage
            mountPath: "/work-dir"
      {{- include "siebel.imagePullSecrets" . | nindent 6 }}
      volumes:
      {{- range $index, $val := .Values.storage }}
        - name: sfs-storage-{{ $index }}
          persistentVolumeClaim:
            claimName: fsspvc-sfs-{{ $index }}
            readOnly: false
      {{- end }}
        - name: persist-storage
          persistentVolumeClaim:
            claimName: fsspvc-persist
            readOnly: false
        - name: keystore
          secret:
            defaultMode: 420
            secretName: keystore
      {{- if .Values.logging.enableLogging }}
        - name: log-collector-config-volume
          configMap:
            name: log-collector-config
      {{- end }}
      {{- if .Values.monitoring.enableMonitoring }}
        - name: prometheus-jmx-config
          configMap:
            name: prometheus-jmx-config
      {{- end }}
      securityContext:
        fsGroup: 1000
