apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: cm-siebel-image-policy
  namespace: {{ .Release.Namespace }}
spec:
  imageRepositoryRef:
    name: cm-siebel-image
  filterTags:
    pattern: {{ template "tag.regex" . }}
    extract: '$num'
  policy:
     numerical:
      order: asc
