apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: cm-siebel-image
  namespace: {{ .Release.Namespace }}
spec:
  image: {{ template "siebel.image" . }}
  interval: 1m0s
  secretRef:
    name: customsecret

