---
apiVersion: batch/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Job
metadata:
  name: image-builder
  namespace: {{ .Release.Namespace }}
  labels: {{- include "siebel.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-builder-job
  annotations:
    ## This is what defines this resource as a hook. Without this line, the job is considered part of the release
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: list-svc-sa
      containers:
        - image: {{ template "siebel.customImageBuilderImage" . }}
          securityContext:
            privileged: true
          name: image-builder
          imagePullPolicy: Always
          env:
            - name: LogLevel
              value: "INFO"
            - name: LogLocation
              value: /output/image_builder.log
            - name: LogLevel
              value: "INFO"
            - name: LogLocation
              value: /output/image_builder.log
            - name: tag
              value: {{ .Values.image.siebel.tag }}
            - name: base_image
              value: {{ .Values.image.siebel.base_image }}
            - name: env_name
              valueFrom:
                 configMapKeyRef:
                   name: siebel-common-config
                   key: ENV_NAME
            - name: tenancy_namespace
              valueFrom:
                 configMapKeyRef:
                   name: siebel-common-config
                   key: TENANCY_NAMESPACE
            - name: GIT_USER
              valueFrom:
                 configMapKeyRef:
                   name: siebel-common-config
                   key: GIT_USER
            - name: GIT_ACCESS_TOKEN
              valueFrom:
                 secretKeyRef:
                   name: siebel-secrets
                   key: GIT_ACCESS_TOKEN
            - name: GIT_HELMCHART_URL
              valueFrom:
                 configMapKeyRef:
                   name: siebel-common-config
                   key: GIT_HELMCHART_URL
            - name: registry_url
              valueFrom:
                 configMapKeyRef:
                   name: siebel-common-config
                   key: REGISTRY_URL
            - name: registry_user
              valueFrom:
                 configMapKeyRef:
                   name: siebel-common-config
                   key: REGISTRY_USER
            - name: registry_password
              valueFrom:
                 secretKeyRef:
                   name: siebel-secrets
                   key: REGISTRY_PASSWORD
          volumeMounts:
            - name: persist-storage
              mountPath: /output
              subPath: {{ .Release.Namespace | upper }}/IMAGE_BUILDER
          {{- if eq .Values.git.git_protocol_type "ssh" }}
            - name: ssh-config
              mountPath: "/home/opc/private_key.pem"
              subPath: private_key.pem
            - name: ssh-config
              mountPath: "/home/opc/ssh_config"
              subPath: ssh_config
          {{- end }}
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "1"
              memory: 4Gi
      initContainers:
        - name: fix-mount
          image: {{ template "siebel.busyboxImage" . }}
          imagePullPolicy: {{ .Values.image.busybox.imagePullPolicy }}
          command:
            - sh
            - -c
            - mkdir -p /work-dir/{{ .Release.Namespace | upper }}/IMAGE_BUILDER;
              chown -R 1000:1000 /work-dir/{{ .Release.Namespace | upper }}/IMAGE_BUILDER;
          volumeMounts:
          - name: persist-storage
            mountPath: "/work-dir"
      restartPolicy: OnFailure
      imagePullSecrets:
      - name: ocirsecret
      - name: customsecret
      volumes:
        - name: persist-storage
          persistentVolumeClaim:
            claimName: fsspvc-persist
            readOnly: false
        {{- if eq .Values.git.git_protocol_type "ssh" }}
        - name: ssh-config
          secret:
            defaultMode: 420
            secretName: ssh-config
        {{- end }}
      securityContext:
        fsGroup: 1000

