{{- if eq .Values.git.git_protocol_type "ssh" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
    private_key.pem: {{ .Files.Get "ssh_private_key/private_key.pem"  | b64enc }}
stringData:
    ssh_config: |
      Host {{ .Values.git.sshConfig.hostname }}
        User {{ .Values.git.sshConfig.username }}
        IdentityFile {{ .Values.git.sshConfig.privateKeyPath }}
{{- end }}
