apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- files:
  - sync.py
  name: siebel-controller
images:
- name: siebel-operator-base
  newName: phx.ocir.io/siebeldev/cm/siebel-operator-base
kind: Kustomization
resources:
- rbac.yaml
- siebel-operator.yaml
