apiVersion: v1
kind: ServiceAccount
metadata:
  name: get-and-create-configmaps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-and-create-configmaps
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups:
      - ""
      - apps
    resources:
      - configmaps
      - pods
      - deployments
      - statefulsets
      - nodes
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: get-and-create-configmaps-rb
subjects:
- kind: ServiceAccount
  name: get-and-create-configmaps
  apiGroup: ""
roleRef:
  kind: Role
  name: get-and-create-configmaps
  apiGroup: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: siebel-controller-token
  annotations:
    kubernetes.io/service-account.name: get-and-create-configmaps
type: kubernetes.io/service-account-token