---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: siebel-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: siebel.metacontroller.io/v1alpha1
    resource: monitors
  childResources:
  - apiVersion: v1
    resource: configmaps
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://siebel-controller/sync
        timeout: 1800s
    customize:
      webhook:
        url: http://siebel-controller/customize
        timeout: 1800s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: siebel-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siebel-controller
  template:
    metadata:
      labels:
        app: siebel-controller
    spec:
      imagePullSecrets:
          - name: ocirsecret
      serviceAccountName: get-and-create-configmaps
      automountServiceAccountToken: false
      containers:
      - name: controller
        image: siebel-operator-base:CM_24.9.1
        command: ["/bin/bash","-c","python /hooks/sync.py"]
        env:
        - name: LogLocation
          value: "/home/siebel/incremental_changes.log"
        - name: Port
          value: "1025"
        volumeMounts:
        - name: hooks
          mountPath: /hooks
        - name: keystore
          mountPath: /certs/ca.cert.pem
          subPath: ca.cert.pem
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access
          readOnly: true
        securityContext:
          privileged: true
      volumes:
      - name: hooks
        configMap:
          name: siebel-controller
      - name: keystore
        secret:
          secretName: keystore
      - name: kube-api-access
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
              - key: ca.crt
                path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
                path: namespace

---
apiVersion: v1
kind: Service
metadata:
  name: siebel-controller
spec:
  selector:
    app: siebel-controller
  ports:
  - port: 80
    protocol: TCP
    targetPort: 1025
