# Default values for siebel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  busybox:
    registry: phx.ocir.io
    repository: siebeldev/busybox
    tag: latest
    imagePullPolicy: IfNotPresent
  configure:
    registry: phx.ocir.io
    repository: siebeldev/cm/sieb-config
    tag: CM_25.3.0
    imagePullPolicy: IfNotPresent
  dbutils:
    registry: phx.ocir.io
    repository: siebeldev/dx4c/dev/dbutils
    tag: 23.1
    imagePullPolicy: IfNotPresent
  curl:
    registry: phx.ocir.io
    repository: siebeldev/curlimages/curl
    tag: latest
    imagePullPolicy: IfNotPresent
  utils:
    registry: phx.ocir.io
    repository: siebeldev/cm/utils
    tag: 22.12.1
    imagePullPolicy: IfNotPresent

#Storage Information
storage:
  - storageClassName: oci-fss
    nfsServer: dx4c-dev-mt.sub3f36566ba.dx4cdev.oraclevcn.com
    nfsPath: /okepodspv/DEMO-CRM

dbInfo:
  dbTnsAlias: SIEBEL
  tnsconnectString: "(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = siebel-db)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = SIEBEL.localdomain)))"
  dbUser: sadmin
  dbPassword: ''
  tblo: SIEBEL
  tbloPassword: SIEBEL
  defaultTablespace: DATA
  defaultIndexspace: DATA
  SSEROLE: SSE_ROLE
      
ca:
  #ipAddress: 129.213.124.55
  clusterDns: svc.cluster.local

# it should come from other module
dbWallet:
  path: db_wallet

cgw:
  replicas: 3

imagePullSecrets: #Add additional secrets as required if accessing multiple registries, create them prior to helm install
  - ocirsecret
  - customsecret

lang:
  primaryLang: ENU
  otherLangs: ''
