# Default values for siebel.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  siebel:
    registry: phx.ocir.io
    repository: siebeldev/cm/siebel
    tag: "25.6-full"
    imagePullPolicy: IfNotPresent
  busybox:
    registry: phx.ocir.io
    repository: siebeldev/busybox
    tag: latest
    imagePullPolicy: IfNotPresent
  dbutils:
    registry: phx.ocir.io
    repository: siebeldev/dx4c/dev/dbutils
    tag: 23.1
    imagePullPolicy: IfNotPresent
  utils:
    registry: phx.ocir.io
    repository: siebeldev/cm/utils
    tag: 22.12.1
    imagePullPolicy: IfNotPresent

# Storage Information
storage:
  - storageClassName: oci-fss
    nfsServer: dx4c-dev-mt.sub3f36566ba.dx4cdev.oraclevcn.com
    nfsPath: /okepodspv/DEMO-CRM

# Migration Storage Information
migration_storage:
  storageClassName: oci-fss
  nfsServer: dx4c-dev-mt.sub3f36566ba.dx4cdev.oraclevcn.com
  nfsPath: /okepodspv/DEMO-CRM

postinstalldb:
  enabled: true

ca:
  #ipAddress: 129.213.124.55
  clusterDns: svc.cluster.local

# it should come from other module
#Siebel server name cannot be > 12 chars and no - hyphen allowed
siebelServer:
  - profile: "siebsrvr_slc05eow_20210816013850"
    replicas: 2
    # HPA for any metric can be defined as below:
    # Note: The metric has to be defined in prometheus-adapter config map rules for using it in autoscaling.
    # autoscaling:
    #   behavior:
    #     scaleDown:
    #       policies:
    #       - periodSeconds: 200
    #         type: Percent
    #         value: 100
    #       selectPolicy: Disabled
    #     scaleUp:
    #       policies:
    #       - periodSeconds: 900
    #         type: Pods
    #         value: 4
    #       - periodSeconds: 900
    #         type: Percent
    #         value: 100
    #       selectPolicy: Max
    #       stabilizationWindowSeconds: 0
    #   minReplicas: 1
    #   maxReplicas: 3
    #   metrics:
    #   - type: Pods
    #     pods:
    #       metric:
    #         name: percentage_container_cpu_usage_siebserver
    #       target:
    #         averageValue: 65500m
    #         type: AverageValue
    siebsrvr_prefix: lily # length should not be > than 10 , no - (hyphen) is allowed
    # sesResources are set for each siebserver profile
    sesResources:
      limits:
        cpu: "2"
        memory: 12Gi
      requests:
        cpu: "1"
        memory: 4Gi
    # This is the node /pod affinity settings as defined in
    # https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
    affinity: {}
    # env variables to the siebserver pod can be overridden by defining the envlist like below:
    envlist: {}
    # envlist:
    #   - name: SBL_HEAP_OPTS
    #     value: "-Xms700m -Xmx7G"

  - profile: "siebsrvr_slc07ifd_20210815225847"
    replicas: 1
    siebsrvr_prefix: daisy
    sesResources:
      limits:
        cpu: "2"
        memory: 12Gi
      requests:
        cpu: "1"
        memory: 4Gi
    affinity: {}

# it should come from other module
#Sai server name cannot be > 12 chars and no - hyphen allowed
saiServer:
  - profile: "slc07ifd25847"
    replicas: 2
    sai_prefix: tulip # length should not be > than 10 , no - (hyphen) is allowed
    # autoscaling:
    #   behavior:
    #     scaleDown:
    #       policies:
    #       - periodSeconds: 200
    #         type: Percent
    #         value: 100
    #       selectPolicy: Disabled
    #     scaleUp:
    #       policies:
    #       - periodSeconds: 900
    #         type: Pods
    #         value: 4
    #       - periodSeconds: 900
    #         type: Percent
    #         value: 100
    #       selectPolicy: Max
    #       stabilizationWindowSeconds: 0
    #   minReplicas: 1
    #   maxReplicas: 3
    #   metrics:
    #   - type: Pods
    #     pods:
    #       metric:
    #         name: container_cpu_usage_sai
    #       target:
    #         averageValue: 65.5
    #         type: AverageValue

    affinity: {}
    # env variables to the saiserver pod can be overridden by defining the envlist like below:
    envlist: {}
    # envlist:
    #   - name: SBL_HEAP_OPTS
    #     value: "-Xms700m -Xmx7G"

imagePullSecrets: #Add additional secrets as required if accessing multiple registries, create them prior to helm install
  - ocirsecret
  - customsecret

sesTomcatLivenessProbe:
  exec:
    command:
    - bash
    - /config/healthcheck
  initialDelaySeconds: 120
  periodSeconds: 10
  failureThreshold: 3

sesTomcatStartupProbe:
  exec:
    command:
    - bash
    - /config/healthcheck
  initialDelaySeconds: 100
  periodSeconds: 30
  failureThreshold: 16

sesResources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "0.5"
      memory: 1Gi

saiLivenessProbe:
  exec:
    command:
    - bash
    - /config/healthcheck
  initialDelaySeconds: 120
  periodSeconds: 30
  failureThreshold: 10

saiReadinessProbe:
  exec:
    command:
    - bash
    - /config/healthcheck
  initialDelaySeconds: 120
  periodSeconds: 30
  failureThreshold: 16

saiResources:
    limits:
      cpu: "1"
      memory: 4Gi
    requests:
      cpu: "0.5"
      memory: 500Mi

# keyfilebin
encryptionKey:
  path: encryption_wallet

# ldap ssl
ldap:
  enable_ssl: false

# siebel logging related parameters
logging:
  enableLogging: false
  image:
    registry: phx.ocir.io
    repository: siebeldev/cm/fluentd-collector
    tag: v1.15.3
    imagePullPolicy: IfNotPresent
  aggregatorInfo:
    portNo: 24224
    svcName: log-aggregator-svc
  logCollectorResources:
     limits:
       cpu: 500m
       memory: 1Gi
     requests:
       cpu: 250m
       memory: 512Mi

#siebel postinstall loglevel can be changed by adding the logs below
# logs:
#   siebelLogEvents: "5"
#   dbUtilLogEvents: "SQLParseAndExecute=5,SQLDBUtilityLog=5"

logs: {}


sai:
  wait4dbconn: true
  wait4cgw: true

ses:
  wait4dbconn: true
  wait4cgw: true

monitoring:
  enableMonitoring: false
