{{- if .Values.postinstalldb.enabled -}}
#Repo Upgrade yaml
---
apiVersion: batch/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Job
metadata:
  name: postinstalldb
  namespace: {{ .Release.Namespace }}
  labels: {{- include "siebel.labels" . | nindent 4 }}
    app.kubernetes.io/component: postinstalldb-job
  annotations:
    ## This is what defines this resource as a hook. Without this line, the job is considered part of the release
    "helm.sh/hook": pre-install,pre-upgrade
    #"helm.sh/hook-delete-policy": before-hook-creation  ## This is default hence commented
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: list-svc-sa
      containers:
        - image: {{ template "siebel.image" . }}
          name: ses
          imagePullPolicy: {{ .Values.image.siebel.imagePullPolicy | default "IfNotPresent" }}
          command: 
            - /bin/bash 
            - -c
            - /config/postinstall.sh
          volumeMounts:
            - name: fs-persist
              mountPath: /persistent
              subPath: {{ .Release.Namespace | upper }}/SES/POSTINSTALLDB
            - name: tns-admin
              mountPath: /tnsadmin
            - name: script
              mountPath: /config/postinstall.sh
              subPath: postinstall.sh
          env:
            - name: PRIMARY_LANG_CD
              valueFrom:
                configMapKeyRef:
                  name: siebel-common-config
                  key: PRIMARY_LANG_CD
            - name: OTHER_LANG_CD
              valueFrom:
                configMapKeyRef:
                  name: siebel-common-config
                  key: OTHER_LANG_CD
            - name: TNS_CONNECT_STRING
              valueFrom:
                configMapKeyRef:
                  name: siebel-common-config
                  key: DBTNSALIAS
            - name: TNS_ADMIN
              value: "/tnsadmin"
            - name: ODBC_DSN
              value: "SIEBELDB"
            - name: TBLO
              valueFrom:
                configMapKeyRef:
                  name: siebel-common-config
                  key: DBTBLO
            - name: TBLOUSER
              valueFrom:
                configMapKeyRef:
                  name: siebel-common-config
                  key: DBTBLO
            - name: TBLOPASS
              valueFrom:
                secretKeyRef:
                  name: siebel-secrets
                  key: DBTBLOPASSWORD
            - name: SIEBUSER
              valueFrom:
                configMapKeyRef:
                  name: siebel-common-config
                  key: DBUSER
            - name: SIEBELUSERPASS
              valueFrom:
                secretKeyRef:
                  name: siebel-secrets
                  key: DBUSERPASSWORD
            - name: TBLSPC
              valueFrom:
                configMapKeyRef:
                  name: siebel-common-config
                  key: DBDEFAULTTABLESPACE
            - name: INDSPC
              valueFrom:
                configMapKeyRef:
                  name: siebel-common-config
                  key: DBDEFAULTINDEXSPACE
            - name: SSE_ROLE
              valueFrom:
                configMapKeyRef:
                  name: siebel-common-config
                  key: DBSSEROLE
            - name: SIEBEL_LOG_DIR
              value: "/persistent"
              {{- if .Values.logs.dbUtilLogEvents }}
            - name: DBUTIL_LOG_EVENTS
              value: {{ .Values.logs.dbUtilLogEvents | quote }}
              {{- end }}
              {{- if .Values.logs.siebelLogEvents }}
            - name: SIEBEL_LOG_EVENTS
              value: {{ .Values.logs.siebelLogEvents | quote }}
              {{- end }}
            - name: sesServername
              value: "SES"
          securityContext:
              runAsUser: 1000
      {{- include "siebel.imagePullSecrets" . | nindent 6 }}
      initContainers:
        - name: fix-mount
          imagePullPolicy: {{ .Values.image.busybox.imagePullPolicy | default "IfNotPresent" }}
          image: {{ template "busybox.image" . }}
          command: 
            - sh
            - -c
            - mkdir -p /work-dir/{{ .Release.Namespace | upper }}/SES/POSTINSTALLDB;
              chown -R 1000:1000 /work-dir/{{ .Release.Namespace | upper }}/SES/POSTINSTALLDB;
          volumeMounts:
          - name: fs-persist
            mountPath: "/work-dir"
      restartPolicy: Never
      volumes:
      - name: fs-persist
        persistentVolumeClaim:
          claimName: fsspvc-persist
          readOnly: false
      - name: tns-admin
        secret:
          secretName: tns-secret
      - name: script
        configMap:
          name: postinstalldb
          defaultMode: 0777
      securityContext:
        #Allowing Non-Root users to access FS
        fsGroup: 1000
{{- end -}}
