# Persistent volume info for Siebel Migration FS
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: siebel-migration-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.migration_storage.storageClassName | quote }}
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  mountOptions:
  - nosuid
  nfs:
    server: {{ .Values.migration_storage.nfsServer | quote }}
    path: {{ .Values.migration_storage.nfsPath | quote }}
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: migration-fs
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.migration_storage.storageClassName | quote }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
    # Although storage is provided here it is not used for FSS file systems
      storage: 10Gi
  volumeName: siebel-migration-{{ $.Release.Namespace }}
