#Configmap for secret keyfilebin
#---
{{- $path := printf "%s/keyfile.bin" .Values.encryptionKey.path }}
{{- $path := .Files.Glob $path }}
{{ if $path }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keyfile-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: siebel
type: Opaque
data:
{{- $filename := printf "%s/keyfile.bin" .Values.encryptionKey.path }}
  keyfile.bin: {{ .Files.Get $filename | b64enc }}
{{- end }}
