# Siebel common config kubernetes yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: siebel-common-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "siebel.labels" . | nindent 4 }}
data:
  #DBINFO
  DBTNSALIAS: {{ .Values.dbInfo.dbTnsAlias }}
  DBTNSCONNECTSTRING: {{ .Values.dbInfo.tnsconnectString }}
  DBUSER: {{ .Values.dbInfo.dbUser }}
  DBTBLO: {{ .Values.dbInfo.tblo }}
  DBDEFAULTTABLESPACE: {{ .Values.dbInfo.defaultTablespace }}
  DBDEFAULTINDEXSPACE: {{ .Values.dbInfo.defaultIndexspace }}
  DBSSEROLE: {{ .Values.dbInfo.SSEROLE }}
  ENV_NAME: {{ .Values.siebel.env_name }}
  TENANCY_NAMESPACE: {{ .Values.siebel.tenancy_namespace | quote }}
  GIT_USER: {{ .Values.git.git_user }}
  GIT_HELMCHART_URL: {{ .Values.git.git_helm_repo_url }}
  GIT_CA_CERT_PATH: {{ .Values.git.git_selfsigned_cacert }}
  REGISTRY_URL: {{ .Values.registry.registry_url }}
  REGISTRY_USER: {{ .Values.registry.registry_user }}
  PRIMARY_LANG_CD: {{ .Values.lang.primaryLang }}
  OTHER_LANG_CD: {{ .Values.lang.otherLangs }}