apiVersion: v1
kind: Secret
metadata:
  name: keystore
  namespace: {{ .Release.Namespace }}
  labels: {{- include "siebel.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
    keystore.jks: {{ .Files.Get "keystore/keystore.jks"  | b64enc }}
    truststore.jks: {{ .Files.Get "keystore/truststore.jks"  | b64enc }}
    ca.cert.pem: {{ .Files.Get "tls_certs/ca.cert.pem"  | b64enc }}
    ca.key.pem: {{ .Files.Get "tls_certs/ca.key.pem"  | b64enc }}
    server.pem: {{ .Files.Get "tls_certs/server.pem"  | b64enc }}
