{{- $ldap_wallet_path := printf "ldap_wallet/ewallet.p12" }}
{{- $ldap_wallet_path := .Files.Glob $ldap_wallet_path }}
{{ if $ldap_wallet_path }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ldap-wallet
  namespace: {{ .Release.Namespace }}
  labels: {{- include "siebel.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
    ewallet.p12: {{ .Files.Get "ldap_wallet/ewallet.p12"  | b64enc }}
{{- end }}