{{- range $index, $val := .Values.storage }}
#Persistent volume info for Siebel FS
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsspv-siebel-{{ $.Release.Namespace }}-{{ $index }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- include "siebel-sfs.storage" $val | nindent 2 }}
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  mountOptions:
  - nosuid
  nfs:
    server: {{ $val.nfsServer | quote }}
    path: {{ $val.nfsPath | quote }}
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsspvc-sfs-{{ $index }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- include "siebel-sfs.storage" $val | nindent 2 }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
    # Although storage is provided here it is not used for FSS file systems
      storage: 10Gi
  volumeName: fsspv-siebel-{{ $.Release.Namespace }}-{{$index}}
{{- if eq $index 0 }}
#Persistent volume info for Siebel Persistence
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsspv-persist-{{ $.Release.Namespace }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- include "siebel-sfs.storage" $val | nindent 2 }}
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  mountOptions:
  - nosuid
  nfs:
    server: {{ $val.nfsServer | quote }}
    path: {{ $val.nfsPath | quote }}
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fsspvc-persist
  namespace: {{ $.Release.Namespace }}
spec:
  {{- include "siebel-sfs.storage" $val | nindent 2 }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
    # Although storage is provided here it is not used for FSS file systems
      storage: 10Gi
  volumeName: fsspv-persist-{{ $.Release.Namespace }}
{{- end -}}
{{- end -}}
