---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: list-svc-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-svc-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: list-svc-rolebind
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: list-svc-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: list-svc-role
  apiGroup: rbac.authorization.k8s.io