# siebel-secrets kubernetes yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: siebel-secrets
  namespace: {{ .Release.Namespace }}
  labels: {{- include "siebel.labels" . | nindent 4 }}
type: Opaque
data:
  DBUSERPASSWORD: {{ .Values.dbInfo.dbPassword | b64enc }}
  DBTBLOPASSWORD: {{ .Values.dbInfo.tbloPassword | b64enc }}
  GIT_ACCESS_TOKEN: {{ .Values.git.git_accesstoken | b64enc }}
  REGISTRY_PASSWORD: {{ .Values.registry.registry_password | b64enc }}

