#Configmap for connect string
---
apiVersion: v1
kind: Secret
metadata:
  name: tns-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: siebel
  annotations:
    ## This is what defines this resource as a hook. Without this line, the job is considered part of the release
    "helm.sh/hook":  pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
{{- $path := printf "%s/*" .Values.dbWallet.path }}
{{ (.Files.Glob $path).AsSecrets | nindent 2  }}

